name: GitHub Pages

on:
  push:
    branches:
      - main  gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Set up environment variables
        run: |
          echo "REACT_APP_API_KEY_WEATHER=${{ secrets.REACT_APP_API_KEY_WEATHER }}" >> $GITHUB_ENV
          echo "REACT_APP_API_KEY_MAP=${{ secrets.REACT_APP_API_KEY_MAP }}" >> $GITHUB_ENV

      - name: Build and deploy
        run: |
          npm run build          
          npm run deploy
